# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-19 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('task', models.CharField(max_length=200)),
                ('is_done', models.BooleanField(default=False)),
                ('task_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.Dashboard')),
            ],
        ),
    ]
